apiVersion: v1
kind: Service
metadata:
  name: actividad-final-cesar-osorio-service
spec:
  selector:
    app: actividad-final-cesar-osorio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # Puerto en el nodo para acceder desde fuera (puede cambiarlo según prefieras)
  type: NodePort
